### ISSUE TITLE
Getting mysql error even though I am using postgres and haven't specified mysql anywhere

### ISSUE THREAD

**Issue by samphilipd** [janko-m/sinatra-activerecord#49]
This issue has had me tearing my hair out for the past two hours. It works perfectly on my development machine but when trying to run on AWS I continually get this exception:

```
[deploy@donotcall-medium1 20150402214023]$ bundle exec rake db:migrate
rake aborted!
Specified 'mysql' for database adapter, but the gem is not loaded. Add `gem 'mysql'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-activerecord-2.0.6/lib/sinatra/activerecord.rb:41:in `database='
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1216:in `set'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-activerecord-2.0.6/lib/sinatra/activerecord.rb:35:in `database_file='
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1216:in `set'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-activerecord-2.0.6/lib/sinatra/activerecord.rb:19:in `registered'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1399:in `block in register'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1397:in `each'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1397:in `register'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1977:in `register'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2038:in `register'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-activerecord-2.0.6/lib/sinatra/activerecord.rb:55:in `<module:Sinatra>'
/home/deploy/.bundler/fosubo_donotcall/ruby/2.1.0/gems/sinatra-activerecord-2.0.6/lib/sinatra/activerecord.rb:10:in `<top (required)>'
/srv/www/fosubo_donotcall/releases/20150402214023/app.rb:4:in `require'
/srv/www/fosubo_donotcall/releases/20150402214023/app.rb:4:in `<top (required)>'
/srv/www/fosubo_donotcall/releases/20150402214023/Rakefile:3:in `require'
/srv/www/fosubo_donotcall/releases/20150402214023/Rakefile:3:in `<top (required)>'
(See full trace by running task with --trace)
```

I don't understand why this is happening. I am not using mysql. I don't want to use mysql. I want to use postgres. I haven't specified mysql anywhere in the project.

```
➜  fosubo-donotcall git:(master) ack mysql
➜  fosubo-donotcall git:(master)
```

Here is my Rakefile:

```
require File.expand_path('../app.rb', __FILE__)
require 'sinatra/activerecord/rake'
```

My Gemfile

```
source "https://rubygems.org"
ruby "2.1.5"
gem 'sinatra'
gem 'pg'
gem 'haml'
gem 'thin'
gem 'json'
gem "sinatra-activerecord"
gem "rake"
```

And my app.rb (first five lines only)
```
require 'haml'
require 'json'
require 'sinatra'
require 'sinatra/activerecord' # EXCEPTION HAPPENS HERE
require "./config/boot"
```

Why is this happening and what can I do to fix it?

**Comment by samphilipd** [comment]
I FIXED IT.

Turns out there was some badly configured opsworks scripts that created a config/database.yml referring to a mysql adapter even though the RDS instance was running postgres.

Not a bug in sinatra-activerecord.

-S

**Comment by alexpchin** [comment]
@samphilipd I'm still getting this error and I can't trace it down? I appreciate that it might not be a bug in sinatra-activerecord. Could you shed any more light?
